name: dumpinfo
version: '0.1'
summary: DumpInfo program
description: |
  A small utility to display system information.

grade: devel
confinement: devmode

parts:
  dumpinfo:
    plugin: python
    python-version: python2
    source: .

apps:
  dumpinfo:
    command: bin/dumpinfo.py
