name: obs-studio
adopt-info: obs
base: core20
grade: stable
confinement: strict
license: GPL-2.0
architectures:
  - build-on: amd64
compression: lzo

parts:
  obs:
    plugin: cmake
    source: https://github.com/obsproject/obs-studio.git
    # ... (many other settings omitted for brevity)
    override-prime: |
      snapcraftctl prime
      # Symlink libaom.so to where StreamFX expects to find it
      rm ${SNAPCRAFT_PRIME}/usr/share/obs/obs-plugins/StreamFX/libaom.so
      cd ${SNAPCRAFT_PRIME}/usr/share/obs/obs-plugins/StreamFX/
      ln -s ../../../../lib/${SNAPCRAFT_ARCH_TRIPLET}/libaom.so .
