name: multiple-build-for
version: "1.0"
summary: test
description: |
  Snap with two platform entries that both list amd64 under build-on.
confinement: strict
base: core24
platforms:
  platform1:
    build-on: [amd64]
    build-for: [amd64]
  platform2:
    build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  nil:
    plugin: nil
